"""empty message

Revision ID: 1aa3c912dc6b
Revises: 2486764d0c9b
Create Date: 2025-06-16 00:05:02.451617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa3c912dc6b'
down_revision = '2486764d0c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('code_expire')

    # ### end Alembic commands ###
