"""empty message

Revision ID: 7abcca1542dc
Revises: 1aa3c912dc6b
Create Date: 2025-06-16 10:29:07.968108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abcca1542dc'
down_revision = '1aa3c912dc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
